# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket            = "shermin-ho-tfstate-."
    enable_versioning = true
    encrypt           = true
    key               = "./terraform.tfstate"
    region            = "ap-southeast-1"
    use_lockfile      = true
  }
}
