# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region  = "ap-southeast-1"
  profile = "shermin"

  default_tags {
    tags = {
      Project   = "shermin-ho"
      ManagedBy = "terragrunt"
    }
  }
}
